# Generated by Django 3.2.12 on 2022-04-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_add_todo_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='assigned_to',
        ),
        migrations.AlterField(
            model_name='todo',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
