# Generated by Django 3.2.12 on 2022-04-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateField(blank=True)),
                ('post_text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='blog/images')),
            ],
        ),
    ]
